# permissions for end users to view natsuseraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernats
    app.kubernetes.io/managed-by: kustomize
  name: auth-natsuseraccount-viewer-role
rules:
- apiGroups:
  - auth.kubernats.ai
  resources:
  - natsuseraccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.kubernats.ai
  resources:
  - natsuseraccounts/status
  verbs:
  - get
