---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.kubernats.ai
  resources:
  - jetstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubernats.ai
  resources:
  - jetstreams/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kubernats.ai
  resources:
  - jetstreams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - auth.kubernats.ai
  resources:
  - natsuseraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.kubernats.ai
  resources:
  - natsuseraccounts/finalizers
  verbs:
  - update
- apiGroups:
  - auth.kubernats.ai
  resources:
  - natsuseraccounts/status
  verbs:
  - get
  - patch
  - update
